source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Swig' do
pod 'GoogleMaps'
pod 'Mapbox-iOS-SDK', '~> 3.2.0'
end

target 'SwigTests' do

end

target 'SwigUITests' do

end

